### ISSUE TITLE
Need further documentation or/and example to use attributes feature

### ISSUE THREAD

**Issue by nicknolt** [gabdube/pyshaders#2]
I know how to use attributes with the opengl binding of pyglet but i have abandoned the idea to use it with pyshaders.

The documentation/usage/example for uniform is very well, could we have the same for attributes please?

Whatever, thanks to your work!

**Comment by gabdube** [comment]
I added a better example for the attribute. Tell me what you think

**Comment by nicknolt** [comment]
This is really great, many thanks :)
I was secretly hoping that pyshaders and pyglet vertex_list would be more tidly linked ...

**Comment by ptb99** [comment]
I'm still learning my around this stuff, but it seems to me that if you create your pylet vertex_list with formats '0g3f' and '1g4i' etc., then these will automatically get bound to the attributes in the shader code.  Trying to understand what other form of "tidy linkage" @nicknolt would be looking for...
